FROM rocker/r-ver:4.0.2

# ARG WHEN

# Magick++
ARG IM_VERSION=7.0.10-25

RUN dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    yum -y update

WORKDIR /opt

RUN yum install -y libtool-ltdl libjpeg libjpeg-devel libpng libpng-devel libtiff libtiff-devel libwebp libwebp-devel LibRaw LibRaw-devel jxrlib git make automake gcc pkgconf ghostscript-core && \
    git clone https://github.com/ImageMagick/ImageMagick.git && \
    cd ImageMagick && git checkout ${IM_VERSION} && \
    ./configure && make && make install && \
    cd ../ && \
    rm -rf ./ImageMagick && \
    yum remove -y git make automake gcc libjpeg-devel libpng-devel libtiff-devel libwebp-devel LibRaw-devel && \
    yum clean all


#sudo apt install libgsl-dev
#libxml2-devel
#sudo add-apt-repository -y ppa:opencpu/imagemagick
 #  sudo apt-get update
  # sudo apt-get install -y libmagick++-dev
   
   
   
   
# Make the home directory
RUN mkdir -p ~/IMPCStatsPipeline/jobs
CMD cd ~/IMPCStatsPipeline/jobs
# 
# RUN wget https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R
# RUN Rscript "install_dependencies.R"
RUN R -e "source('https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R')"


# RUN mkdir ~/mydocker/results 
# docker run -v ~/mydocker/results:/home/IMPCStatsPipeline  analysis
