FROM rocker/r-ver:4.0.2

# ARG WHEN

WORKDIR /IMPC_SP

# zlib
RUN apt install -y zlib1g

# XML package
#RUN apt-get -y purge -f libxml2-dev
#RUN apt-get -y clean
RUN apt-get -y update
RUN apt-get -y install libxml2 libxml2-dev


# GSL package
RUN apt install -y libgsl-dev

# Magick++
RUN apt update 
RUN apt-get -y install build-essential
ADD https://www.imagemagick.org/download/ImageMagick.tar.gz ImageMagick.tar.gz
#RUN mkdir -p ImageMagick
RUN tar xvzf ImageMagick.tar.gz 
WORKDIR ImageMagick-7.0.10-27
#RUN cd ImageMagick-7.0.10-27
RUN echo $(ls -ah)
RUN chmod 775 configure
RUN ./configure
RUN make
RUN make install 



   
   
   
# Make the home directory
RUN mkdir -p ~/IMPCStatsPipeline/jobs
CMD cd ~/IMPCStatsPipeline/jobs
# 
# RUN wget https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R
# RUN Rscript "install_dependencies.R"
RUN R -e "source('https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R')"


# RUN mkdir ~/mydocker/results 
# docker run -v ~/mydocker/results:/home/IMPCStatsPipeline  analysis
