FROM rocker/r-ver:4.0.2

# ARG WHEN

# Magick++



RUN apt install libgsl-dev
RUN apt install libxml2-devel
RUN add-apt-repository -y ppa:opencpu/imagemagick
RUN apt-get update
RUN apt-get install -y libmagick++-dev
   
   
   
   
# Make the home directory
RUN mkdir -p ~/IMPCStatsPipeline/jobs
CMD cd ~/IMPCStatsPipeline/jobs
# 
# RUN wget https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R
# RUN Rscript "install_dependencies.R"
RUN R -e "source('https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R')"


# RUN mkdir ~/mydocker/results 
# docker run -v ~/mydocker/results:/home/IMPCStatsPipeline  analysis
