FROM rocker/r-ver:3.4.4

# ARG WHEN


# Make the home directory
RUN mkdir /home/IMPCStatsPipeline/jobs
COPY jobs /home/IMPCStatsPipeline/jobs

# 
CMD wget https://raw.githubusercontent.com/mpi2/impc_stats_pipeline/master/impc_statistical_pipeline/install_dependencies.R
RUN Rscript install_dependencies.R


# update the data from impress
RUN R -e "DRrequiredAgeing:::updateImpress(updateImpressFileInThePackage = TRUE,updateOptionalParametersList = TRUE,updateTheSkipList = TRUE,saveRdata = FALSE)"

# RUN mkdir ~/mydocker/results 
# docker run -v ~/mydocker/results:/home/IMPCStatsPipeline  analysis
